logging:
    level:
        root: INFO

spring:
    application:
        name: Firefly
    profiles:
        active: development
        
---

spring:
    profiles: test
firefly:
    core:
        fps: 2 # Frames per second
        heartbeat: 10000 # If there is only one frame to show, 
                         # in what interval (in milliseconds) we will resend it to receivers
        
---

spring:
    profiles: development
firefly:
    server:
        hostname: localhost
        port: 8080
    core:
        fps: 4
        heartbeat: 10000
        
---

spring:
    profiles: release
firefly:
    server:
        hostname: localhost
        port: 3000
    core:
        fps: 4
        heartbeat: 10000