logging:
    level:
        root: INFO

spring:
    application:
        name: Firefly
    profiles:
        active: release
        
---

spring:
    profiles: test
firefly:
    core:
        fps: 2 # Frames per second
        heartbeat: 10000 # If there is only one frame to show, 
                         # in what interval (in milliseconds) we will resend it to receivers
        timerThreads: 1 # How many threads we use with timer
        
---

spring:
    profiles: development
firefly:
    core:
        fps: 4
        heartbeat: 2000
        timerThreads: 1
    serialPort:
        name: /dev/ttyUSB0
    server:
        hostname: localhost
        port: 8080
        
---

spring:
    profiles: release
firefly:
    core:
        fps: 20
        heartbeat: 14000
        timerThreads: 4
    serialPort:
        name: /dev/ttyUSB0
    server:
        hostname: localhost
        port: 3000