logging:
    level:
        root: INFO

spring:
    application:
        name: Firefly
    profiles:
        active: development
        
---

spring:
    profiles: test
firefly:
    core:
        fps: 2 # Frames per second
        
---

spring:
    profiles: development
firefly:
    server:
        hostname: localhost
        port: 8080
    core:
        fps: 4 # Frames per second
        
---

spring:
    profiles: release
firefly:
    server:
        hostname: localhost
        port: 3000
    core:
        fps: 4 # Frames per second